version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - django_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 5
      start_period: 10s

  web:
    build: .
    container_name: django_app
    restart: always
    working_dir: /app
    command: >
      sh -c "make migrate &&
             python manage.py runserver 127.0.0.1:11001"
    volumes:
      - .:/app
    ports:
      - "11001:11001"
    environment:
      - DB_HOST=db  # Use the service name here
      - DB_NAME=backend
      - DB_USER=root
      - DB_PASSWORD=root
      - ALLOWED_HOSTS=0.0.0.0,127.0.0.1,localhost
      - DEBUG=False
    depends_on:
      db:
        condition: service_healthy
    networks:
      - django_network

volumes:
  mysql_data:

networks:
  django_network:
    driver: bridge
