name: CD pipeline

on:
  workflow_run:
    workflows: ["CI pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull rohanchauhan02/loan-service:latest
      - name: Delete Old container
        run: docker rm -f loan-service-container || true
      - name: Run Docker Container
        run: docker run -d -p 8080:8080 --name loan-service-container rohanchauhan02/loan-service
